#!/usr/bin/env zsh
directory-update-time() {
  local dirPath="$1"
  if [ -z "$dirPath" ]; then
    echo-error "Directory path is required."
    return $CODE_ERROR
  fi
  local prefix="$(format-cmd 'directory-update-time')"
  local fileName=$(directory-last-file-updated $dirPath)
  local updateTime=$(file-update-time "$fileName")
  if [ -z "$updateTime" ]; then
    echo "0"
  else
    echo "$updateTime"
  fi
}
