#!/usr/bin/env zsh
each-file-recursive() {
    local root_dir="$1"
    local command="$2"
    local prefix=$(format-cmd 'each-file-recursive')
    shift 2
    echo-debug "$prefix Recursively processing files in $(format-args "$root_dir") with command: $(format-args "$command"). Args: $@"
    find "$root_dir" -type f -print0 | sort -z | while IFS= read -r -d $'\0' file; do
        echo-verbose-debug "$(format-cmd 'each-file-recursive') Processing file: $(format-args "$file")"
        eval "$command" "$file" "$@"
    done
}