#!/usr/bin/env zsh
link-file() {
    local prefix=$(format-cmd "link-file")
    local src="$1"
    local srcDir="${src:h}"
    local dest="$2"
    local destDir="${dest:h}"
    mkdir -p "$destDir"
    local pointingTo=$(link-pointing-to "$dest")
    # echo "$src       >>>          $dest"
    local pointingToMessage=""
    local confirmLinking=false
    if [[ -n "$pointingTo" ]]; then
        # local pointingToFormatted=$(format-args "$pointingTo")
        if [[ "$pointingTo" == "$src" ]]; then
            pointingToMessage=" (already linked)"
        else
            pointingToMessage=" (was linked to $(format-args "$pointingTo"))"
            confirmLinking=true
        fi
    else
        confirmLinking=true
    fi
    
    local message="$prefix $(format-args "$src") > $(format-args "$dest")$pointingToMessage"
    
    if [[ "$confirmLinking" == true ]]; then
        ln -sf "$src" "$dest"
        echo-success "$message"
    else
        echo-info "$message"
    fi
}