#!/usr/bin/env zsh
link-directory-recursive-cached() {
    local directoryFrom="$1"
    local directoryTo="$2"

    shift 2

    local prefix=$(format-cmd 'link-directory-recursive-cached')

    local directoryFromFormatted=$(format-args "$directoryFrom")
    local directoryToFormatted=$(format-args "$directoryTo")

    trace-add "$prefix Checking for cached linking from $directoryFromFormatted to $directoryToFormatted"

    if [[ -z "$directoryFrom" || -z "$directoryTo" ]]; then
        echo-error "$prefix Missing required arguments: directoryFrom and directoryTo."
        return $CODE_ERROR
    fi

    local cacheFilePath="$directoryFrom.shu.hash"
    local cacheFilePathFormatted=$(format-args "$cacheFilePath")

    if [[ ! -f "$cacheFilePath" ]]; then
        echo-debug "$prefix Cache file not found. Running linking."
        link-directory-recursive "$directoryFrom" "$directoryTo" "$@"
        echo "$(directory-update-time "$directoryFrom")" > "$cacheFilePath"
        trace-add "$prefix Cache file created at $cacheFilePathFormatted"
        return $CODE_SUCCESS
    fi

    local savedHash=$(cat "$cacheFilePath")
    local currentHash=$(directory-update-time "$directoryFrom")
    if [[ "$currentHash" != "$savedHash" ]]; then
        echo-debug "$prefix Cache file hash does not match current hash. Running linking."
        link-directory-recursive "$directoryFrom" "$directoryTo" "$@"
        echo "$currentHash" > "$cacheFilePath"
        trace-add "$prefix Cache file updated at $cacheFilePathFormatted"
        return $CODE_SUCCESS
    fi
    trace-add "$prefix Cache file at $cacheFilePathFormatted didn't change, skipping linking."
}