#!/usr/bin/env zsh
local message=$1
local prefix="$(format-cmd 'git-fast-commit')"
local statusSimple=$(git-status-simple)
# if statusSimple have no lines, skip committing
if [[ -z "$statusSimple" ]]; then
    echo-info "$prefix No changes to commit"
    return 0
fi

if [[ -z "$message" ]]; then
    local newMessage=$(x-gum input --placeholder "Commit message")
    if [[ -z "$newMessage" ]]; then
        echo-error "Commit message is required."
        return $CODE_ERROR
    fi
    message="$newMessage"
fi
echo-info "$prefix Fast commit with message: $(format-args "$message")"
git commit --no-verify -m "$message" ${@:2}