#!/usr/bin/env zsh
confirm-command() {
    local command="$@"
    local commandFormatted=$(format-args "$command")
    local prefix="$(format-cmd "confirm-command")"
    gum confirm "Execute command '$commandFormatted'?" || {
        echo-info "$prefix Command '$commandFormatted' was not confirmed."
        return $CODE_NOT_FOUND
    }
    echo-debug "$prefix Command '$commandFormatted' was confirmed."
    eval "$command"
    local returnCode=$?
    if [[ $returnCode -ne 0 ]]; then
        echo-error "Command '$commandFormatted' failed with return code $returnCode."
    else
        echo-success "Command '$commandFormatted' executed successfully."
    fi
    return $returnCode
}