#!/usr/bin/env zsh
source-if-exists() {
    local fileName="$1"

    local prefix=$(format-cmd 'source-if-exists')
    local fileNameFormatted=$(format-args "$fileName")

    if [ -f "$fileName" ]; then
        source "$fileName"
        trace-add "$prefix Sourced $fileNameFormatted."
    else
        echo-error "$prefix File $fileNameFormatted does not exist, skipping source"
    fi
}