#!/usr/bin/env zsh
source-raw-directory-mapper() {
    local file="$1"
    if [[ -f "$file" ]]; then
        local fileNameFormatted=$(format-args "$file")
        echo-debug "$prefix Sourcing file: $fileNameFormatted"
        source "$file"
        trace-add "$prefix Sourced file $fileNameFormatted"
    fi
}