#!/usr/bin/env zsh
(
    local commandName=$1
    shift
    local currentTime=$(get-time-ms)
    $commandName "$@"
    local endTime=$(get-time-ms)
    local elapsedTime=$(($endTime - $currentTime))
    echo-info "Command $(format-args "$commandName") took $elapsedTime ms to execute."
)